services:
  emdr:
    build: .
    container_name: emdr
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emdr.rule=Host(`emdr.andragia.fr`)"
      - "traefik.http.routers.emdr.entrypoints=websecure"
      - "traefik.http.services.emdr.loadbalancer.server.port=3000"
      - "traefik.http.routers.emdr.tls=true"
      - "traefik.http.routers.emdr.tls.certresolver=le"
    networks:
      - web
      - internal

networks:
  web:
    external: true
  internal:
    external: false
